file_ext: .c .cpp .h .hpp
sections:
  - caption: License Header
    pattern: (?<=\A)(//-*\n(//.*\n)*//-*\n)*
    comment: |
      //------------------------------------------------------------------------------
      // {file:LICENSE}
      //------------------------------------------------------------------------------
  - caption: Scope Separator
    pattern: (?<=^}\n\n)(?://-*\n)*
    comment: |
      //------------------------------------------------------------------------------
  - caption: End of File
    pattern: (?://-*\n(?://.*\n)*)*(?=\Z)
    comment: |
      //------------------------------------------------------------------------------
      // end of file
