file_ext: .py
sections:
  - caption: License Header
    pattern: (?<=\A)(#-*\n(#.*\n)*#-*\n)*
    comment: |
      #-------------------------------------------------------------------------------
      # {file:LICENSE}
      #-------------------------------------------------------------------------------
  - caption: Function Separator
    pattern: (#-*\n)*(?=^def )
    comment: |-
      #-------------------------------------------------------------------------------
  - caption: End of File
    pattern: (?:#-*\n(?:#.*\n)*)*(?=\Z)
    comment: |
      #-------------------------------------------------------------------------------
      # end of file
